### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by shuangwu42** [5orenso/geo-lib#3]
When running 'npm install geo-lib' it will show errors below. Only running 'npm install --no-bin-links geo-lib' works

> npm WARN purplepipe-consumers@1.0.0 No license field.
> npm ERR! Darwin 15.5.0
> npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "install" "geo-lib"
> npm ERR! node v5.3.0
> npm ERR! npm  v3.10.5
> npm ERR! path /Users/shuangwu/dataLab/purplepipe-consumers/node_modules/geo-lib/bin/geo-lib
> npm ERR! code ENOENT
> npm ERR! errno -2
> npm ERR! syscall chmod
> npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/shuangwu/dataLab/purplepipe-consumers/node_modules/geo-lib/bin/geo-lib'
> npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/shuangwu/dataLab/purplepipe-consumers/node_modules/geo-lib/bin/geo-lib'
> npm ERR! enoent This is most likely not a problem with npm itself
> npm ERR! enoent and is related to npm not being able to find a file.
> npm ERR! enoent
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/shuangwu/dataLab/purplepipe-consumers/npm-debug.log

**Comment by 5orenso** [comment]
Removed unused section in package.json.
